version: '3.7'

services:
  # ref link: https://github.com/localstack/localstack/blob/master/docker-compose.yml
  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - 4566:4566
    # environment variables details: https://docs.localstack.cloud/references/configuration/
    environment:
      - EDGE_PORT=4566
      - SERVICES=s3
    volumes:
      - ./volume:/var/lib/localstack
  backend:
    build:
      context: src
      dockerfile: Dockerfile-dev
    restart: always
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./src/:/app/
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://dummy_pg_user:dummy_pg_pwd@db/dummy_pg_db
      - TEST_DATABASE_URL=postgresql://dummy_pg_tuser:dummy_pg_tpwd@db_test/dummy_pg_tdb
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - SUPERUSER_LOGIN=dummy_login
      - SUPERUSER_PWD=dummy&P@ssw0rd!
      - BUCKET_NAME=sample-bucket
      - S3_ENDPOINT_URL=http://s3.localhost.localstack.cloud:4566
      - S3_ACCESS_KEY=fake
      - S3_SECRET_KEY=fake
      - S3_REGION=us-east-1
    depends_on:
      - db
      - localstack
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dummy_pg_user
      - POSTGRES_PASSWORD=dummy_pg_pwd
      - POSTGRES_DB=dummy_pg_db
  db_test:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data_test/
    environment:
      - POSTGRES_USER=dummy_pg_tuser
      - POSTGRES_PASSWORD=dummy_pg_tpwd
      - POSTGRES_DB=dummy_pg_tdb

volumes:
  postgres_data:
  postgres_data_test:
