version: '3.7'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  backend:
    build:
      context: src
      dockerfile: Dockerfile-dev
    restart: always
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./src/:/app/
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://dummy_pg_user:dummy_pg_pwd@db/dummy_pg_db
      - TEST_DATABASE_URL=postgresql://dummy_pg_tuser:dummy_pg_tpwd@db_test/dummy_pg_tdb
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - SUPERUSER_LOGIN=dummy_login
      - SUPERUSER_PWD=dummy&P@ssw0rd!
      - BUCKET_NAME=sample-bucket
      - S3_ENDPOINT_URL=http://s3.localhost.localstack.cloud:4566
      - S3_ACCESS_KEY=fake
      - S3_SECRET_KEY=fake
      - S3_REGION=us-east-1
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dummy_pg_user
      - POSTGRES_PASSWORD=dummy_pg_pwd
      - POSTGRES_DB=dummy_pg_db
  db_test:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_test:/var/lib/postgresql/data_test/
    environment:
      - POSTGRES_USER=dummy_pg_tuser
      - POSTGRES_PASSWORD=dummy_pg_tpwd
      - POSTGRES_DB=dummy_pg_tdb

volumes:
  postgres_data:
  postgres_data_test:
